pip install error fix
package_dir removed from setup.py for causing this;

```bash
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      running egg_info
      creating /tmp/pip-pip-egg-info-ppzpuwql/decentra_network.egg-info
      writing /tmp/pip-pip-egg-info-ppzpuwql/decentra_network.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-pip-egg-info-ppzpuwql/decentra_network.egg-info/dependency_links.txt
      writing entry points to /tmp/pip-pip-egg-info-ppzpuwql/decentra_network.egg-info/entry_points.txt
      writing top-level names to /tmp/pip-pip-egg-info-ppzpuwql/decentra_network.egg-info/top_level.txt
      writing manifest file '/tmp/pip-pip-egg-info-ppzpuwql/decentra_network.egg-info/SOURCES.txt'
      error: package directory 'decentra_network/decentra_network' does not exist
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```